// KargoOnayMerkezi.styles.js
export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1400px",
    margin: "0 auto",
    background: "#0a0a0a",
    minHeight: "100vh",
    fontFamily: "inherit",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    flexWrap: "wrap",
    gap: "20px",
  },
  title: {
    margin: 0,
    fontSize: "28px",
    fontWeight: "700",
    color: "#fff",
    letterSpacing: "-0.5px",
  },
  subtitle: {
    margin: "8px 0 0 0",
    fontSize: "14px",
    color: "#888",
    fontWeight: "400",
  },
  datePickerContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    background: "#1a1a1a",
    padding: "16px",
    borderRadius: "12px",
    border: "1px solid #2a2a2a",
  },
  dateLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: "#888",
    fontWeight: "500",
  },
  dateInput: {
    background: "#0f0f0f",
    color: "white",
    border: "1px solid #333",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "14px",
    cursor: "pointer",
    outline: "none",
  },
  statsBar: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    marginBottom: "24px",
  },
  statCard: {
    background: "linear-gradient(135deg, #1a1a1a 0%, #252525 100%)",
    padding: "20px",
    borderRadius: "12px",
    border: "1px solid #2a2a2a",
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  statIcon: { fontSize: "32px" },
  statValue: { fontSize: "24px", fontWeight: "700", color: "#fff" },
  statLabel: { fontSize: "12px", color: "#888" },
  primaryButton: {
    padding: "16px 32px",
    background: "linear-gradient(135deg, #4caf50 0%, #45a049 100%)",
    color: "white",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "0.3s",
  },
  replanBar: {
    background: "linear-gradient(135deg, #1a1a1a 0%, #252525 100%)",
    padding: "20px",
    borderRadius: "12px",
    border: "1px solid #f39c12",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
  },
  replanTitle: { fontSize: "16px", fontWeight: "600", color: "#f39c12" },
  secondaryButton: {
    padding: "12px 24px",
    background: "#f39c12",
    color: "white",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
  },
  tabContainer: {
    display: "flex",
    gap: "12px",
    marginBottom: "24px",
    borderBottom: "2px solid #1a1a1a",
  },
  activeTab: {
    padding: "14px 24px",
    background: "#4caf50",
    color: "white",
    border: "none",
    borderRadius: "10px 10px 0 0",
    cursor: "pointer",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  inactiveTab: {
    padding: "14px 24px",
    background: "transparent",
    color: "#666",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  badge: {
    background: "rgba(255, 255, 255, 0.2)",
    padding: "2px 8px",
    borderRadius: "12px",
    fontSize: "12px",
    marginLeft: "8px",
  },
  tableContainer: {
    background: "#1a1a1a",
    borderRadius: "12px",
    border: "1px solid #2a2a2a",
    overflow: "hidden",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    padding: "16px",
    textAlign: "left",
    color: "#4caf50",
    fontSize: "13px",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  td: { padding: "16px", color: "#e0e0e0", fontSize: "14px" },
  tableRow: {
    borderBottom: "1px solid #1a1a1a",
    transition: "0.2s",
    cursor: "pointer",
  },
  senderName: { fontWeight: "600", color: "#fff" },
  senderEmail: { fontSize: "12px", color: "#666" },
  stationBadge: {
    background: "#252525",
    padding: "6px 12px",
    borderRadius: "8px",
    border: "1px solid #333",
  },
  weightBadge: {
    background: "#1a2332",
    color: "#64b5f6",
    padding: "6px 12px",
    borderRadius: "8px",
    fontWeight: "600",
  },
  destinationBadge: {
    background: "#1a2a1a",
    color: "#4caf50",
    padding: "6px 12px",
    borderRadius: "8px",
    fontWeight: "600",
  },
  statusBadge: (durum) => ({
    padding: "6px 12px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: "600",
    background: durum === "Beklemede" ? "#332200" : "#1a2a1a",
    color: durum === "Beklemede" ? "#ffa726" : "#4caf50",
    border: `1px solid ${durum === "Beklemede" ? "#4a3300" : "#2d4a2d"}`,
  }),
  // Styles dosyana şu alanı ekle veya güncelle
thCheckbox: {
  padding: "16px",
  width: "60px",
  textAlign: "center",
  borderBottom: "2px solid #2a2a2a",
  background: "#0f0f0f"
},
checkboxContainer: {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  cursor: "pointer",
  transition: "transform 0.2s"
},
// Hover efekti için
checkboxHover: {
  transform: "scale(1.1)"
}
};
