export const styles = {
  container: {
    padding: "20px",
    background: "#0a0a0a",
    minHeight: "100vh",
    color: "#fff",
    fontFamily: "sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "25px",
    borderBottom: "1px solid #222",
    paddingBottom: "20px",
  },
  statsContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "15px",
    marginBottom: "25px",
  },
  statCard: {
    background: "linear-gradient(135deg, #1a1a1a 0%, #252525 100%)",
    padding: "20px",
    borderRadius: "12px",
    border: "1px solid #333",
    display: "flex",
    alignItems: "center",
    gap: "15px",
  },
  statValue: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    color: "#fff",
    lineHeight: 1,
  },
  statLabel: { fontSize: "0.85rem", color: "#888", marginTop: "3px" },
  statIcon: {
    fontSize: "2rem",
    width: "50px",
    height: "50px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#333",
    borderRadius: "10px",
  },
  mainLayout: {
    display: "flex",
    gap: "20px",
    height: "calc(100vh - 320px)",
    minHeight: "600px",
  },
  sidebar: { width: "350px", overflowY: "auto", paddingRight: "10px" },
  content: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    overflowY: "auto",
  },
  routeCard: {
    padding: "18px",
    borderRadius: "10px",
    marginBottom: "12px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    border: "1px solid #222",
  },
  rotaBanner: {
    background: "linear-gradient(135deg, #1a1a1a 0%, #252525 100%)",
    padding: "20px",
    borderRadius: "12px",
    border: "1px solid #333",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  mapWrapper: {
    height: "400px",
    minHeight: "400px",
    width: "100%",
    borderRadius: "12px",
    border: "1px solid #333",
    overflow: "hidden",
    position: "relative", // Leaflet için kritik
  },
  tableWrapper: {
    background: "#1a1a1a",
    padding: "20px",
    borderRadius: "12px",
    border: "1px solid #333",
    flex: 1,
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    textAlign: "left",
    padding: "12px",
    borderBottom: "2px solid #333",
    color: "#4caf50",
    fontSize: "0.9rem",
    position: "sticky",
    top: 0,
    background: "#1a1a1a",
  },
  td: {
    padding: "14px 12px",
    borderBottom: "1px solid #222",
    fontSize: "0.9rem",
  },
  dateBox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "#1a1a1a",
    padding: "10px 18px",
    borderRadius: "8px",
    border: "1px solid #333",
  },
  dateInput: {
    background: "transparent",
    color: "#fff",
    border: "none",
    outline: "none",
    cursor: "pointer",
  },
};
